export const ACTION_TYPE = {
  INITIAL_DATA: "INITIAL_DATA",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  MOVE_TO_CART: "MOVE_TO_CART",
  INC_QTY: "INC_QTY",
  DEC_QTY: "DEC_QTY",
};
